### OPERATION ON NUMPY ARRAY

In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing: \n", arr[2:7])
print("Slicing with step: \n", arr[1:9:2])
print("Slicing with negative step: \n", arr[9:1:-2])
print("Slicing with negative step: \n", arr[-2])




Basic slicing: 
 [3 4 5 6 7]
Slicing with step: 
 [2 4 6 8]
Slicing with negative step: 
 [10  8  6  4]
Slicing with negative step: 
 9


In [10]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array: \n", arr_2d)
print("Specific element: \n", arr_2d[1, 2])
print("Whole row: \n", arr_2d[1])
print("Whole column: \n", arr_2d[:, 2])

2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element: 
 6
Whole row: 
 [4 5 6]
Whole column: 
 [3 6 9]


## Sorting


In [11]:
unsorted_arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
sorted_arr = np.sort(unsorted_arr)
print("Sorted array: \n", sorted_arr)

arr_2d = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])

sorted_arr_2d = np.sort(arr_2d, axis=0)
print("Sorted 2D array along columns: \n", sorted_arr_2d)

sorted_arr_2d_rows = np.sort(arr_2d, axis=1)
print("Sorted 2D array along rows: \n", sorted_arr_2d_rows)

Sorted array: 
 [1 1 2 3 4 5 5 6 9]
Sorted 2D array along columns: 
 [[1 1 4]
 [2 5 5]
 [3 6 9]]
Sorted 2D array along rows: 
 [[1 3 4]
 [1 5 9]
 [2 5 6]]


# Filter

In [12]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: \n", even_numbers)

Even numbers: 
 [ 2  4  6  8 10]


#  Filter with mask

In [13]:
mask = numbers > 5
filtered_numbers = numbers[mask]
print("Filtered numbers: \n", filtered_numbers)

Filtered numbers: 
 [ 6  7  8  9 10]


In [ ]:
indices = [0, 2, 4]
subset = numbers[indices]
print("Subset: \n", subset)

where_result = np.where(numbers > 5)
print("Indices where condition is true: \n", where_result)
subset_where = numbers[where_result]
print("Subset using np.where: \n", subset_where)



Subset: 
 [1 3 5]
Indices where condition is true: 
 (array([5, 6, 7, 8, 9]),)
Subset using np.where: 
 [ 6  7  8  9 10]


In [17]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print("Condition array: \n", condition_array)

Condition array: 
 [ 1  2  3  4  5 24 28 32 36 40]


### Adding and Removind data      

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print("Combined array: \n", combined)

combined = np.concatenate((arr1, arr2))
print("Combined array using concatenate: \n", combined)

Combined array: 
 [5 7 9]
Combined array using concatenate: 
 [1 2 3 4 5 6]


### Array compatibilty

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 10])

print("Compatibility shapes: \n", a.shape == b.shape)
print("Compatibility shapes: \n", a.shape == c.shape)

Compatibility shapes: 
 True
Compatibility shapes: 
 False


In [23]:
original = np.array([[1, 2], [3, 4], [5, 6]])
new_row = np.array([[7, 8]])
new_col = np.array([[9], [10], [11]])
modified_row = np.vstack((original, new_row))
print("Modified array with new row: \n", modified_row)
modified_col = np.hstack((original, new_col))
print("Modified array with new column: \n", modified_col)   

Modified array with new row: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Modified array with new column: 
 [[ 1  2  9]
 [ 3  4 10]
 [ 5  6 11]]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
deleted_element = np.delete(arr, 2)
print("Array after deletion: \n", deleted_element)

Array after deletion: 
 [1 2 4 5]
