### NUMPY FOUNDATION

In [6]:
import numpy as np

## Creating array from list


In [7]:
arr_id = np.array([1, 2, 3, 4, 5])
print(arr_id)

arr_id2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_id2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List vs numpy array


In [11]:
py_list = [1, 2, 3, 4, 5]
print("python list multiplication:", py_list * 2)

np_arr = np.array([1, 2, 3, 4, 5])
print("numpy array multiplication:", np_arr * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Python list comprehension time:", time.time() - start)

start = time.time()
np_arr = np.arange(1000000) * 2
print("Numpy array multiplication time:", time.time() - start)

python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
numpy array multiplication: [ 2  4  6  8 10]
Python list comprehension time: 0.11721110343933105
Numpy array multiplication time: 0.008252859115600586


### creating array from scratch


In [16]:
zeros = np.zeros((3,4))
print("zeroes array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,2), 7)
print("full array: \n", full)

random_arr = np.random.random((2,3))
print("random array: \n", random_arr) 

sequence = np.arange(0, 11, 2)
print("sequence array: \n", sequence)

zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.99208135 0.27823951 0.40994972]
 [0.19290865 0.72122602 0.77929951]]
sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [17]:
vector = np.array([1, 2, 3])
print("vector: \n", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("tensor: \n", tensor)



vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties


In [22]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Size:", arr.size)

arr = np.array([[1,2,3],
                [4,5,True]])

print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Size:", arr.size)

arr = np.array([[1,2,3],
                [4,5,"6"]])

print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Size:", arr.size)

arr = np.array([[1,2,3],
                [4,5,6.0]])

print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Size:", arr.size)


Shape: (2, 3)
Number of dimensions: 2
Data type: int64
Size: 6
Shape: (2, 3)
Number of dimensions: 2
Data type: int64
Size: 6
Shape: (2, 3)
Number of dimensions: 2
Data type: <U21
Size: 6
Shape: (2, 3)
Number of dimensions: 2
Data type: float64
Size: 6


Array Reshaping

In [29]:
# arr = np.array([[1,2,3],
#                 [4,5,6.0]], dtype=int)  

# print("Shape:", arr.shape)
# print("Number of dimensions:", arr.ndim)    
# print("Data type:", arr.dtype)
# print("Size:", arr.size)

arr = np.arange(12)
print("Original array:", arr)   
arr_reshaped = arr.reshape((3, 4))
print("Reshaped array (3, 4):\n", arr_reshaped)

flattened = arr_reshaped.flatten()
print("Flattened array:", flattened)

# ravel (returns view, not a copy)
reveled = arr_reshaped.ravel()
print("Raveled array:", reveled)

# Transpose
transposed = arr_reshaped.T
print("Transposed array:\n", transposed)

# adjoint (conjugate transpose)
adjoint = arr_reshaped.conj().T
print("Adjoint array:\n", adjoint)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Adjoint array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
